import type { MovementManifest } from "./core/types.js";

export const movementCatalog = [
  {
    slug: "passband-lens",
    name: "Passband Lens",
    summary: "Inspect one procedural terrain plate through optical, thermal, radar, and semantic bands.",
    technology: "WebGL2",
    categories: ["data visualization", "sensing", "storytelling"],
    capabilities: ["desktop", "touch", "reduced motion", "static fallback"],
    accessibility: "Band controls remain native buttons. Reduced motion and unavailable WebGL use a static contact sheet.",
    sourcePath: "kits/passband-lens",
  },
  {
    slug: "orbit-trail",
    name: "Orbit Trail",
    summary: "A chapter-aware pointer trail expands from a local structure into an orbital instrument.",
    technology: "Canvas 2D",
    categories: ["storytelling", "decorative cursor"],
    capabilities: ["desktop", "reduced motion", "static fallback"],
    accessibility: "The visualization is decorative and never carries required chapter information.",
    sourcePath: "kits/orbit-trail",
  },
  {
    slug: "system-assembly",
    name: "System Assembly",
    summary: "Technical segments assemble around the pointer and respond to nearby capability domains.",
    technology: "Canvas 2D",
    categories: ["data visualization", "decorative cursor"],
    capabilities: ["desktop", "reduced motion", "static fallback"],
    accessibility: "Capability content remains semantic HTML outside the decorative canvas.",
    sourcePath: "kits/system-assembly",
  },
  {
    slug: "active-links",
    name: "Active Links",
    summary: "The pointer connects to nearby nodes and visualizes active relationships.",
    technology: "Canvas 2D",
    categories: ["navigation", "data visualization"],
    capabilities: ["desktop", "reduced motion", "static fallback"],
    accessibility: "All relationships and destinations must remain available in semantic HTML.",
    sourcePath: "kits/active-links",
  },
  {
    slug: "pathfinder",
    name: "Pathfinder",
    summary: "An orthogonal route follows the pointer toward the nearest evidence or action target.",
    technology: "Canvas 2D",
    categories: ["navigation", "storytelling"],
    capabilities: ["desktop", "keyboard", "reduced motion"],
    accessibility: "Targets retain native focus, activation, and visible focus treatment.",
    sourcePath: "kits/pathfinder",
  },
  {
    slug: "terrain-scanner",
    name: "Terrain Scanner",
    summary: "A comet-like scanner moves across a website surface and briefly reveals procedural terrain beneath it.",
    technology: "Canvas 2D",
    categories: ["data visualization", "sensing"],
    capabilities: ["desktop", "touch", "reduced motion", "static fallback"],
    accessibility: "The stage is decorative and accompanied by a text description of every scan state.",
    sourcePath: "kits/terrain-scanner",
  },
  {
    slug: "layered-reveal",
    name: "Layered Reveal",
    summary: "A moving brush erases a Something Old website layer to uncover a looping Something New film.",
    technology: "Canvas 2D",
    categories: ["reveal", "storytelling"],
    capabilities: ["desktop", "touch", "reduced motion", "static fallback"],
    accessibility: "Both layers need meaningful nearby copy when they communicate information.",
    sourcePath: "kits/layered-reveal",
  },
  {
    slug: "magnetic-ink",
    name: "Magnetic Ink",
    summary: "Particles gather around the pointer, write on press, and scatter after a quick reversal.",
    technology: "Canvas 2D",
    categories: ["particles", "drawing", "decorative cursor"],
    capabilities: ["desktop", "touch", "reduced motion", "static fallback"],
    accessibility: "Touch may use long press, while reduced motion receives a still field with the native cursor.",
    sourcePath: "kits/magnetic-ink",
  },
  {
    slug: "constellation-wand",
    name: "Constellation Wand",
    summary: "The pointer bends a graph, highlights paths, and selects neutral destinations.",
    technology: "Canvas 2D",
    categories: ["navigation", "data visualization"],
    capabilities: ["desktop", "touch", "keyboard", "list fallback"],
    accessibility: "An accessible list remains the canonical navigation surface.",
    sourcePath: "kits/constellation-wand",
  },
  {
    slug: "fusion-field",
    name: "Fusion Field",
    summary: "A comet cursor moves through a binary vortex and scatters digits according to speed.",
    technology: "Canvas 2D",
    categories: ["particles", "decorative cursor", "storytelling"],
    capabilities: ["desktop", "reduced motion", "static fallback"],
    accessibility: "Text response is decorative and the original text remains readable and selectable.",
    sourcePath: "kits/fusion-field",
  },
] as const satisfies readonly MovementManifest[];

export function getMovement(slug: string) {
  return movementCatalog.find((movement) => movement.slug === slug);
}
